### ISSUE TITLE
Seeders cache

### ISSUE THREAD

**Issue by ilyalatt** [alanmcgovern/monotorrent#221]
@alanmcgovern Hello!

Looks like the library disconnects from peers in StoppingMode. And if there is a need in a new file download then a request to a tracker/DHT is needed. What do you think about seeders cache? The library can try to connect to peers from the last time concurrently. There are torrents that have seeders with static IP address that seed all the day. It guess it can enhance performance for cases when you need to download a small file by request of an user often but the torrent manager stays in StoppedMode a lot of time.

**Comment by alanmcgovern** [comment]
I think you're suggesting that the list of peers should not be cleared when stopping a torrent ( https://github.com/alanmcgovern/monotorrent/blob/82b9083aeb80fdd8e4ed0b94bbe3538004bac09a/src/MonoTorrent/MonoTorrent.Client/Modes/StoppingMode.cs#L62 ) ? If so that should be an easy change and could help alright. What i would recommend in this scenario is that if a torrent is in the 'stopped' state and is started, any Peers still left in the list should be marked as 'probably not ok', and then when the first announce completes (if it ever completes) any peer still marked as 'probably not ok' should be removed from the list and then the list should be filled with the peers we just received from the tracker.

The idea would be that we start with a list of old peers, and at the earliest opportunity replace any peers we have not connected to with the fresh  ones from the tracker/dht.

Further caching beyond would likely be of limited benefit. Ideally torrents would not be started/stopped frequently. Ideally they would be started and then left running. This would increase the pool of seeders to improve download speeds overall. If your application only runs torrents when the client needs additional data then the overall health of the swarm will be reduced.

**Comment by ilyalatt** [comment]
> The idea would be that we start with a list of old peers, and at the earliest opportunity replace any peers we have not connected to with the fresh ones from the tracker/dht.

Yeah, this is what I mean. As you can see it is hard for me to express my thoughts :)

> Further caching beyond would likely be of limited benefit. Ideally torrents would not be started/stopped frequently. Ideally they would be started and then left running. This would increase the pool of seeders to improve download speeds overall. If your application only runs torrents when the client needs additional data then the overall health of the swarm will be reduced.

Yeah, I understand it. I try to find a reason why there are cases when it it takes really long time to download a file after a big idle period. The list of seeds of the torrent stays the same. If I rerun the app and try to download the file that stuck after idling it is downloaded as usual this time. So I thought maybe the torrent manager stops itself after idling and resets a peers list. This assumption is wrong, so I need to search somewhere else, but I have found the issue :)

**Comment by alanmcgovern** [comment]
I understood you perfectly :)

I pushed a change which should do the trick. I suspect it'll break some tests so I'll review the tests and add new ones covering the change before merging it. In the meantime please do check it out! 

https://github.com/alanmcgovern/monotorrent/tree/retain-peers

Thanks!

**Comment by alanmcgovern** [comment]
This should be implemented in master now! If you can think of any tweaks to make this better do let me know!
