### ISSUE TITLE
Question: StreamProvider to RAM

### ISSUE THREAD

**Issue by mfkl** [alanmcgovern/monotorrent#277]
Hello,

I am wondering whether it would be possible/make sense to have a way to keep the stream in memory instead of on disk. The API would define the cache size for the stream (say 200MB) and dispose/download the relevant torrent parts as the stream plays, for example.

Does that make sense?

**Comment by alanmcgovern** [comment]
It does make sense. 

The issue with this approach is that it can lead to a scenario where leechers will rarely be able to share data with each other as they don't retain enough of the pieces they downloaded. This would put the burden of uploading on first seeder, which would then result in very poor torrent performance.

Why do you want to avoid writing pieces to disk, and why do you want to discard pieces in the middle of a download session? Maybe there's another way to achieve the task you want to achieve?

**Comment by mfkl** [comment]
> leechers will rarely be able to share data with each other as they don't retain enough of the pieces they downloaded

Yes, that's a valid concern. How much % of the total size would allow for reasonable sharing in your opinion?

> Why do you want to avoid writing pieces to disk, and why do you want to discard pieces in the middle of a download session? 

I'm just wondering how someone who would go about implementing a media streaming client with monotorrent on devices that have little to no storage space available (mobile I guess) or high security constraints.

**Comment by alanmcgovern** [comment]
> Yes, that's a valid concern. How much % of the total size would allow for reasonable sharing in your opinion?

That's a hard one to judge as it depends on how many seeds there are and where they are in the stream. If they're all more or less in sync it won't be a problem. If they are essentially random then one way to calculate it is that if each peer retains 10% of the data then you need 10 leechers to act like 1 seeder.
> 
> I'm just wondering how someone who would go about implementing a media streaming client with monotorrent on devices that have little to no storage space available (mobile I guess) or high security constraints.

It'd be relatively easy, though it would require a more complete implementiom of the DoNotHave message to properly advertise a piece is no longer available. 

At the simplest level all you'd need to do would be to make DiskManager use a MemoryWriter instead of a DiskWriter. Extra logic would be needed to ensure pieces which are discarded do cause a "DoNotHave" message to be sent.

One tweak to ensure randomised picking is disabled, and also that the manager only downloads data in the HighPrioity set. Currently it downloads pieces in the high priority set first, then it does random piece picking across the entire range of pieces.

**Comment by mfkl** [comment]
Cool, thanks for the info 👍

**Comment by alanmcgovern** [comment]
I'd definitely be interested in taking patches to support this usecase, and could contribute a bit towards it to if you wanted to try implement it!

**Comment by mfkl** [comment]
> if you wanted to try implement it

I might :-) Will keep you posted if I do!

For now just playing with a sample https://github.com/mfkl/libvlcsharp/blob/da97c430f5bbd14b92b9c9e8cb203c49bd594016/Samples/LibVLCSharp.NetCore.Sample/Program.cs
