### ISSUE TITLE
Use separate IO thread per TorrentManager

### ISSUE THREAD

**Issue by vlasenkoalexey** [alanmcgovern/monotorrent#286]
I understand decision to move all IO to a separate thread, it makes code cleaner and causes less issues with synchronization.

Also it has drawbacks.
If you download one big file to a faster drive (local hdd) and a torrent with bunch of smaller files on a slow drive (external USB flash drive), download speed will be limited to a speed of a slower drive. In my tests first download didn't finish until second one was completed.

**Comment by alanmcgovern** [comment]
The intention is to make DiskManager use async read/write methods, and then try to do a per storage media queue of sorts. That way writes to fast storage would never be 'queued' alongside writes to slow storage.

**Comment by alanmcgovern** [comment]
This is being tracked as part of https://github.com/alanmcgovern/monotorrent/tree/unstable-vnext . This is the first big API break, but there will be a few more before the next release :)

If you want to test this new version it should handle the scenario you described perfectly. Reading/writing is handled on a per-filestream basis now, rather than on an engine level 'one read at a time' basis. It will probably improve performance by giving the native command queuing more work when data is begin written to multiple files.

**Comment by alanmcgovern** [comment]
This issue covers the changes that will be made before the unstable-vnext branch is versioned as `2.0.0` and released https://github.com/alanmcgovern/monotorrent/issues/260
