### ISSUE TITLE
New StreamProvider problem

### ISSUE THREAD

**Issue by uponatime2019** [alanmcgovern/monotorrent#293]
Hello,
I'm using StreamProvider API from first day. I just notice new change in recent releases
- Old API: I can download the file normally, then if I want to stream, just pick a file and it start play
- New API: It's not possible. I must stop remove manager from current engine, then let StreamProvider create new manager.

**Comment by alanmcgovern** [comment]
Yes, this was a deliberate choice for the first release.

There's a little bit of complication around managing the lifespan of the stream and/or TorrentManager. I was able to avoid dealing with those corner cases by hiding the fact a TorrentManager is being used.

It's easy to restore the ability to create a stream from an active TorrentManager. The approach I'd probably take would be to retain the decision to only allow one stream at a time (for now), and then have the stream be disposed of automatically if/when the TorrentManager is stopped or if someone replaces the piece picker in the torrent manager. Also I'd have to change it so that disposing/closing the stream does not stop/unregister the torrent manager.

I reckon the API would be something like:
```TorrentManager.cs
public async Task<StreamProvider> GetStreamProvider ()
{
    // 1) throw an exception if a StreamProvider was returned already and it hasn't been disposed
    // 2) Ensure the stream provider sets up the torrent manager without taking control of it's lifespan (i.e. it won#t call StartAsync/StopAsync etc)
    // 3) Ensure the streamprovider is disposed automatically when the torrentmanager is stopped by the user.

}
```

If you want to play around with the code and submit a PR
