### ISSUE TITLE
Tracker on linux

### ISSUE THREAD

**Issue by justscribe** [alanmcgovern/monotorrent#299]
Hi,

I'm having an issue with starting torrent tracker on ubuntu 18.04.
The response is always 404 (Not Found).
Is it a correct url for tracker, http://host:port/announce/ ?

Thank you.

**Comment by justscribe** [comment]
The problem is definitely with the host.
What should I write to ipaddress:
IPEndPoint(IPAddress.Parse(ipaddress), port);
I'm using a forwarding server and a router, on both I've opened a port for tracker.
So I have, hostname -> forwarding server IP -> router IP -> tracker IP.
On the torrent file I'm writing hostname.

**Comment by justscribe** [comment]
From the local network it works, I mean from the IP like 192.168.*.*.
But from external IP, it's not.

**Comment by alanmcgovern** [comment]
If the port is forwarded correctly from your router then you need to make sure your local server is listening on the right ip address. Have you tried setting IpAddress.Any so it listens on all interfaces?

**Comment by justscribe** [comment]
Yes, I've tried all of the IPAddress types) Only for local IP it listening that port.
I'm checking that by "sudo netstat -nat | grep LISTEN"
I, for testing changed port to 0.0.0.0 (Any) to listen on all interfaces as you mentioned.
With another command "sudo ss -tulpn" I saw that it is in UNCONN state and only UDP listener.
Also I've tried to start it only with HTTP, UDP, BOTH with no luck.
Very strange.

**Comment by alanmcgovern** [comment]
Hrmm, if you can connect to the tracker using localhost when on the machine, or the internal IP address when on another machine on the same network, then it sounds like a port forwarding problem in your router or a firewall issue somewhere. 

Can you confirm I've understood correctly and the tracker is working as expect for hosts on your internal network? If so I'll have a think about ways to diagnose this

**Comment by justscribe** [comment]
Yes, it's working correctly only for Internal nerwork for Linux, and only for localhost on Windows.
But no one app is using that port.

**Comment by justscribe** [comment]
I've deployed a debug version to the server, to see what happening when I'm using IPAddress.Any.
And the error "IPv4 address 0.0.0.0 and IPv6 address ::0 are unspecified addresses that cannot be used as a target address." happens when I'm trying to start HttpListener after registering it.

**Comment by justscribe** [comment]
Also I've turned on logs for tcp connections, when I'm getting 404 error, that happens as I metioned before when IP is for Internal Network, I mean IP that router gave to server, like 192.168.1.XXX.
No one is blocking the connection (firewall, not opened ports, etc), the problem with app.
![image](https://user-images.githubusercontent.com/8200485/82141426-68b04c00-983e-11ea-8d59-c0aa57d0a697.png)

**Comment by alanmcgovern** [comment]
Hrmm... If you're getting a 404 then it means the connection has been received and handled correctly by *something*. 

This means there is something handling these connections and it does look like a .netcore app. 

By any chance is there some default mechanism returning a 404 because thing aren't been set correctly by MonoTorrent? Or have you made a custom listener for the tracker and that's doing something incorrectly?

The prior error about IpAddress.Any not being supported is strange too. 

To save a bit of back and forth, can you share a solution containing a basic .net core application which I can use to test with on my machines?

**Comment by justscribe** [comment]
No, listener is default.
Does my server can cause such problems? But it runs on different port.
Mono tracker implemented as a service of my server, not a standalone app.
Maybe the problem that I incorrectly added it?
See my startup part for ConfigureServices method:
![image](https://user-images.githubusercontent.com/8200485/82152686-b7280f80-986b-11ea-92d7-276a6ef0b8f9.png)
TorrentService imitates BackgroundService.
![image](https://user-images.githubusercontent.com/8200485/82152772-3c132900-986c-11ea-8628-78be9a7715ba.png)
![image](https://user-images.githubusercontent.com/8200485/82152787-53eaad00-986c-11ea-89d7-911853590a7e.png)

**Comment by alanmcgovern** [comment]
If you're running an actual HTTP server somewhere, then i wonder if the problem is that you've configured your firewall/router so it forwards traffic to the HTTP server instead of the MonoTorrent's tracker.

That could also explain why it works fine from a computer on your network and fails when you try to access it via your public IP address.

**Comment by justscribe** [comment]
HTTP server is running, but it is on different port (80, 443), instead of MonoTorrent's tracker, running on 53091 port. Also, my server (where tracker included) is fully accessible from its port via public network, and forwarding configured on the same way.

Ok, I'll try to build a simple alone app for testing.

**Comment by justscribe** [comment]
Hi.
I've built a simple app from mono examples... and the picture is the same or even worse)
First of all, you need to run it with admin rights to start listener with external IP.
I'm getting 404 for all interfaces, IP.Any is not working all all for HTTP listener, only UDP listener always listens the right port.
![image](https://user-images.githubusercontent.com/8200485/82408250-e8732c00-9a73-11ea-9e19-ddcf0cb0326c.png)
Download the test project you can from here: https://mega.nz/file/UkAXGKKS#nR_STHtQStSHp1XdbrmfrBe58RG9DHez-DDiQoiG8cI

**Comment by alanmcgovern** [comment]
@justscribe I just got around to testing this.

On my computer the tracker appears to be responding correctly when i use `IPAddress.Loopback` and then open `http://127.0.0.1:53091/announce` in my browser, but not when listening on IPAddress.Any. This looks like something that changed over the last few years as this used to be supported.

When i checked with `IPAddress.Any` the status on the listener is set to 'PortNotAvailable'. This is slightly confusing in terms of a Http listener, but what it means is that the Http prefix was unavailable. It looks like .NET has decided that listening on `http://0.0.0.0:12345`, or `http://*:12345` is no longer supported. There's a warning in the documentation about using globs ( https://docs.microsoft.com/en-us/dotnet/api/system.net.httplistener?view=netcore-3.1 ).

The suggested approach is to use a domain name (`http://foo.com:12345` or whatever). Perhaps the documentation for .NET will explain why they've disabled this behaviour and the right approach for setting up a http server.

Alternatively there could be other good HTTP server libraries out there which can be used instead of the built-in HttpListener. If that's the case you should be able to create an `ITrackerListener` implementation which fulfills your needs.

This issue is new to me and I don't know how long it'll take me to find the time to research this. As it stands, it's technically not a bug in MonoTorrent. This is the expected behavior of .NET. I would expect that listening on the correct domain name, and then opening `http://that-domain-name.com:53091/announce` in your browser will let things work as expected.

**Comment by justscribe** [comment]
@alanmcgovern Thanks for the detailed response.

I've tried with domain name, and got some strange results, again=)
First of all, I've changed the listener creation way for:
![image](https://user-images.githubusercontent.com/8200485/83723241-0c736780-a647-11ea-95b1-8d50dd0ca007.png)
Where the ipAddress is a domain name, don't be confused)
Greatly, listener is starting, but the address is a bit stange, 127.0.1.1...
Next step, I got response from tracker on the **server machine** by domain name:
![image](https://user-images.githubusercontent.com/8200485/83723592-9fac9d00-a647-11ea-9360-15c052746fe2.png)
But, I can't get response from outside... Outside means, internal network and external network. I've mentioned that port is opened and forwarding configuration is working for other apps.
So for now I decided to return to my PHP implementation of torrent tracker.
Maybe later I will do deeper research.
Thank you.

**Comment by justscribe** [comment]
Haha, for the last try, I've used a warned wildcard, and it's works... From everywhere.

**Comment by boiss-dev** [comment]
> 
> 
> Haha, for the last try, I've used a warned wildcard, and it's works... From everywhere.

You mean, you used something like that ?
`            var announceUrl = "http://*:1000/announce/";
            var listeners = new[] { TrackerListenerFactory.CreateHttp (announceUrl) };`

**Comment by justscribe** [comment]
Yeap.
