### ISSUE TITLE
Replace MonoTorrent.Logger with NLog

### ISSUE THREAD

**Issue by vlasenkoalexey** [alanmcgovern/monotorrent#306]
MonoTorrent.Logger is rather hard to use and configure.
For me it is easier to add Debug.WriteLine to debug issues than configure MonoTorrent.Logger.

NLog is a pretty much standard go to library for .NET logging now.
It is super flexible, supports namespace and message filtering, hot reload and tons of other great features.

Why not replace MonoTorrent.Logger with NLog?
For connection specific stuff you could add extension methods like:

```c#
public static void Info(this NLog.Logger logger, IConnection connection, string message)
{
    logger.Info (connection.ToString () + " : " + message);
}

public static void Debug (this NLog.Logger logger, IConnection connection, string message)
{
    logger.Debug (connection.ToString () + " : " + message);
}
```

**Comment by alanmcgovern** [comment]
Yeah - the built in logger is not great at all. 

I'm a little averse to building in a specific logging framework as I feel most users of the library likely have their own framework of choice.

Perhaps the logging API could be made more pluggable.

**Comment by vlasenkoalexey** [comment]
I bet that on Windows most of people are going to use NLog, not sure about Xamarin or Mono.
If you are going to refactor it, my ask would be to make logger aware of class it is called from, so it is possible to filter events for specific components.

**Comment by mfkl** [comment]
Maybe the logging package from https://github.com/dotnet/extensions could be an option.

**Comment by alanmcgovern** [comment]
I think that's a pretty reasonable idea for an end user to choose. 

However if I were to use that in MonoTorrent itself I'd have to pull in a whole dependency injection framework too. 

My intention is to expand the ILogger interface to provide a way to set the kinds of logging which should be gathered, and then allow a user provided logger to be attached. 

en

**Comment by alanmcgovern** [comment]
NLog is fairly widely used so if either of you were interested in creating/contributing a `MonoTorrent.NLog` library I'd be happy to include it in this repo and ship a nuget package for it. The idea would be that anyone using NLog in their applications would be able to reference that package and have a simple way to push monotorrent logging into NLog.

**Comment by vlasenkoalexey** [comment]
I have my branched version where I just dropped in NLog directly.
Will take a look what it is going to take to abstract it out.

**Comment by alanmcgovern** [comment]
Would something like this be usable for you?

* The `ILogger` interface is a single method which takes an enum and an object[]

https://github.com/alanmcgovern/monotorrent/pull/312/files#diff-e7c627f094543bea93bc7e8eb28882cfR17

* Every loggable event has a unique value in the enum. The xml docs on each enum describe when the logging event will be raised, and describe the objects which will be passed to the logging method.

https://github.com/alanmcgovern/monotorrent/pull/312/files#diff-4607f9986cfcf019dbb89792a6f1bb79R27-R30

* When implementing ILogger you can generate a unique string for each log event, and can safely cast the items in the array to the types described in the xml docs.

https://github.com/alanmcgovern/monotorrent/pull/312/files#diff-7d00eb8edd98fe42bd960caf86397241R27

**Comment by vlasenkoalexey** [comment]
Actually I had a very different idea.
Instead of creating unique enum value per event, make logger implementation class aware.
In other words in every class you want to use logger, you have to define it as
private static readonly MonoTorrent.Logger logger = LogManager.GetCurrentClassLogger();

And then you could log anything using adhoc strings, and it also helps to have helper methods to log connection specific stuff:
public static void Info(IConnection connection, string message)...

Then in logger implementation you could choose to filter events from specific components, which is useful if you want to debug something specific.

This is flexible and consistent with how NLog is working, so plugging in NLog is going to be straightforward.

Here is a sample NLog config to illustrate the idea.
```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      keepVariablesOnReload="true" autoReload="true">

  <targets async="true">
    <target name="logfile" xsi:type="File" fileName="${var:app_local_state_folder}\log.txt" />
    <target name="debugger" xsi:type="OutputDebugString" />
  </targets>

  <rules>
    <logger name="MonoTorrent.Client.*" minlevel="Error" writeTo="debugger" />
    <logger name="MonoTorrent.Client.ConnectionManager" minlevel="Error" writeTo="logfile" >
      <filters>
        <when condition="not contains('${message}','ipv4')" action="Ignore"/>
      </filters>
    </logger>
    
    <logger name="MonoTorrent.UWP.Client" minlevel="Info" writeTo="logfile" />
  </rules>
</nlog>
```

If MonoTorrent user choose to use different library, it will be possible to implement same functionality if necessary. 
What do you think?

**Comment by alanmcgovern** [comment]
Well, I suppose there are a few questions I should ask.

Firstly, my hope is that every will use the MonoTorrent NuGet package. There should be no reason for anyone to make changes to MonoTorrent itself, unless they intend to contribute those changes to me because they're fixing a bug or adding a missing feature.

With that in mind, my first question is - why are you trying to add logging to monotorrent's private classes? This is a very unusual thing for a user of a library to be doing. This kind of logging requires changing monotorrent internals, which means you'd never be able to use the nuget package.

There are three aspects to logging. Which of these are you looking to address as it changes how the implementation is done:

1) Make it easier for developers of the library to understand what's going on.

This can be implemented as you suggested, by having class level loggers which capture the class name. For my own use I'd find this style of logging too unstructured. For example, I would prefer all logging related to piece picking to have the prefix `PiecePicker: ` regardless of which class the log statement came from. It makes filtering logs much simpler, and these logs would be for my benefit, and also for any contributors.

2) Make it easy for users of the library to provide good diagnostics for the developers of the library.

If monotorrent had good internal logging (which it currently does not) then it should be easy for someone using the NuGet package to write those logs to disk and submit them to help diagnose issues.

3) Give users of the application the library is embedded into a high level overview of what's going on inside MonoTorrent.

This is what I was aiming for with my PR. I was looking to provide a very simple public API for someone to integrate with so they can get logging about some, or all, of the aspects of the library which they may not normally get clear visibility into. A user of the MonoTorrent nuget package would implement one method in `ILogger`, then call something like:

`Logger.Enable(new MyLogger (), LogType.IncomingConnection | LogType.OutgoingConnection | LogType.BlockedConnection)`

and then they'd get logging only for those three events. They could also do:

`Logger.Enable (new MyLogger (), LogType.All)` and get logging for everything monotorrent currently exposes.

**Comment by vlasenkoalexey** [comment]
Thanks for detailed explanation, indeed I look at this from the perspective of library developer (your point 1), while your PR is more suitable for library consumers (points 2 and 3).

I think that 1 is most important here, because for 2 it should be pretty easy to compile MonoTorrent instead, and I'm not sure if a lot of people care about 3 (as far as I understand this is kind of messages view in uTorrent).

Regarding implementation, agree that your proposal is more structured. But this will make a bit harder to integrate it with NLog which has a lot of functionality around class names.
How do you feel about combining approaches (making logger class aware and also having enum for component), so it integrates nicely with all log providers, and can be used to address all points you listed? This will give library developers and consumers more flexibility on how they want to use logging.

As for your last question, the only reason I'm not using MonoTorrent from nuget is because I build it for UWP, which still has a lot of quirks (like file access API differences) and extra features (like C++/WRT)

**Comment by alanmcgovern** [comment]
I think this will be a better match for what you're trying to accomplish.

https://github.com/alanmcgovern/monotorrent/commit/e23fadcbe7e0e5d920bf2b22c1964320540e38c3

Internally in monotorrent we can port everything to a `static readonly Logger logger = Logger.Create ()` . This captures the class name. As a consumer of the library you can implement ILogger and then proxy the data to nlog, or do whatever you want.

Does this work for you?

**Comment by vlasenkoalexey** [comment]
Thanks, this is perfect!
Couple of comments: 
- I don't think that it makes sense to add InfoFormatted since it is easier to use $ style string interpolation now.
- It would be nice to add special methods that take IConnection for logging connection specific events.

**Comment by alanmcgovern** [comment]
> I don't think that it makes sense to add InfoFormatted since it is easier to use $ style string interpolation now.

This is an internal implementation detail and so won't be exposed to users of the library. I intend to add several `internal` overloads of these logging methods so that the invocations to the loggers are zero-allocation for the case where no `ILogger` is supplied. Some of the more verbose logging statements could be called thousands of times a second and it'd be a shame if that continually allocated junk `string` instances which were never actually used :)

> It would be nice to add special methods that take IConnection for logging connection specific events.

Those will probably be added internally alright. However for you, a consumer of an unmodified monotorrent (ideally ;) ), the only thing you should ever receive will be two strings [link](https://github.com/alanmcgovern/monotorrent/commit/e23fadcbe7e0e5d920bf2b22c1964320540e38c3#diff-e7c627f094543bea93bc7e8eb28882cfR32-R36). One for the classname and one with the already-formatted logging data. In this setup you'll never receive typed parameters and so won't be able to construct your own logging stirng. However, that's not something a user of a library would need to do anyway so that's fine.

**Comment by vlasenkoalexey** [comment]
Agree, both are valid points. Added couple of comments to https://github.com/alanmcgovern/monotorrent/commit/e23fadcbe7e0e5d920bf2b22c1964320540e38c3
in order to allow injecting loggers that take full class name in a constructor.
And I think it also make sense to add Warning logging.
Other than that looks good.
Thanks for taking time to make it extensible.

**Comment by alanmcgovern** [comment]
Can you take a look at https://github.com/alanmcgovern/monotorrent/commit/e9753c343105442cb6a712dea7be0a8a942ddf33 and see if it's suitable enough. If not - can you make a pull request with suggested changes so I have a better idea what you want to accomplish? I'm flexible :)

There's an Info/Debug/Error in the interface now, which will allow a little bit of variance in what's logged too :)

**Comment by alanmcgovern** [comment]
This has been implemented already and is available in the main branch.

If there are any further tweaks needed just let me know!
