### ISSUE TITLE
[UWP] StreamProvider bugs 

### ISSUE THREAD

**Issue by askovpen** [alanmcgovern/monotorrent#315]
stream from MagnetLink:

await CreateStreamAsync raise exception - Manager.Torrent.Files - null
```C#
public async Task<Stream> CreateStreamAsync (TorrentFile file, bool prebuffer, CancellationToken token)
...
            if (!Manager.Torrent.Files.Contains (file))
```

stream from torrent file:
System.IO.FileNotFoundException: "Could not find file {destFile}"
in
```C#
public override async Task<int> ReadAsync (byte[] buffer, int offset, int count, CancellationToken cancellationToken)
...
 Stream = new FileStream (File.FullPath, FileMode.Open, FileAccess.Read, FileShare.ReadWrite);
```

**Comment by alanmcgovern** [comment]
@askovpen Did you call `StreamProvider.WaitForMetadataAsync` before trying to create the stream? I can add an explicit check for this and throw an exception if it hasn't been done already. The metadata can take a long time to retrieve if you're relying solely on Dht which is why I separated that out.

However i can also make the `CreateStreamAsync` method call `WaitForMetadataAsync` internally you don't have to call that yourself

**Comment by alanmcgovern** [comment]
Actually, now that i've refreshed my memory I don't think there's anything to be changed here.

You can't call CreateStreamAsync until after the metadata has been downloaded as that's the only way to get a `TorrentFile` instance. I'll add an exception which should make this clearer :)

**Comment by alanmcgovern** [comment]
This issue has been addressed by throwing an exception if  `Files` is null. This is an error case as it means an invalid ITorrentFile instance is being passed in, and also the metadata hasn't been downloaded so the actual list of files (`StreamProvider.Files`) hasn't been populated.

Thanks for reporting!
