### ISSUE TITLE
StreamProvider.CreateStreamAsync(torrentFile) Method is Throw,  <System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. Parameter name: index>  When TorrentFileSize bigger than 2GB.

### ISSUE THREAD

**Issue by wizard872** [alanmcgovern/monotorrent#326]
i want to play video with torrent streaming,  i try using monotorrent version(1.0.24) in Unity(2019.3.0f6)

but i have a some problem...  because,

i have same Exception when i try use StreamProvider.CreateStreamAsync(file) Method. in this issue.
https://github.com/alanmcgovern/monotorrent/issues/294

System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: index

this my usage case,
![usage](https://user-images.githubusercontent.com/36080488/92307443-924dd880-efd1-11ea-817c-1bec5041ee97.png)

and i can get this stacktrace

![stacktrace](https://user-images.githubusercontent.com/36080488/92307459-abef2000-efd1-11ea-8624-1fcf4154998b.png)

here is Exception Point.
![제목 없음](https://user-images.githubusercontent.com/36080488/92307460-aeea1080-efd1-11ea-9211-86f9084509b3.png)

i think, TorrentFile size have a relation this exception.
TorrentFile size < 2GB,  it works!
but 
TorrentFile size > 2GB,  i can see this System.ArgumentOutOfRangeException.

my english is bad, sorry,  
but if you check this problem, thankyou so much!

**Comment by alanmcgovern** [comment]
Hi,

I believe this issue has been addressed in https://github.com/alanmcgovern/monotorrent/tree/metadata-mode-improvements. These two combined should be the fix: https://github.com/alanmcgovern/monotorrent/commit/c9b7377502e72218ff73678be093b88998513ef8#diff-81a55598703353f44612cc2a35222b1aR109-R110 and https://github.com/alanmcgovern/monotorrent/commit/c9b7377502e72218ff73678be093b88998513ef8#diff-5f29ff3ec3fd1105dda333f64713f274R251 .

I got distracted and never finalised/landed those changes. If you're compiling monotorrent from source, could you try that branch and see if it allows you to watch that video? Otherwise i can finalise and merge this in the not-too-distant future.

**Comment by wizard872** [comment]
https://github.com/alanmcgovern/monotorrent/tree/metadata-mode-improvements.

i applied this branch codes,  it work on TorrentFile size > 2GB ! nice !

**Comment by RomanPrystaiko** [comment]
Hello @wizard872 could you also publish this fix to nuget gallery.

**Comment by wizard872** [comment]
> Hello @wizard872 could you also publish this fix to nuget gallery. Because I have the same problem v 1.028

@alanmcgovern   umm... not completed this problem. maybe need check the 1.0.28 versions?

**Comment by RomanPrystaiko** [comment]
I am sorry ) I meant @alanmcgovern
