### ISSUE TITLE
ClientEngine.EnablePortForwardingAsync() does not forward DhtEngine udp port

### ISSUE THREAD

**Issue by jpmikkers** [alanmcgovern/monotorrent#328]
Also, I would propose that EnablePortForwarding become an EngineSetting rather than the current Enable/Disable methods.

**Comment by alanmcgovern** [comment]
The DHT thing is definitely a bug, and it's mostly due to how Dht is unnecessarily exposed as a public extensibility point. I can move the Dht thing into an engine setting, along with the port forwarding setting, relatively easily.

https://github.com/alanmcgovern/monotorrent/tree/immutable-settings

My intention is to make EngineSettings immutable. You can modify them using an EngineSettingsBuilder. When you have a new instance configured correctly, you will call `await ClientEngine.UpdateSettingsAsync (TorrentSettings)`.

Inside this method I'll be able to update any listeners to use the new `ListenPort` or `DhtPort` (if needed), forward any ports, or unforward the old ones, etc. It an also enable/disable port forwarding if i make it a setting too, like you suggest.

Would this approach work for you?

**Comment by jpmikkers** [comment]
Sounds great!

**Comment by alanmcgovern** [comment]
This should be fixed in master. If you can build from source it would be great if you could give it a shot.

I won't release an update to nuget.org for a few days, at least, as I want to let this bake a bit more. It's a fairly large change overall!

Do let me know how you get on.

**Comment by jpmikkers** [comment]
Hehe just trying this update I noticed the EngineSettingsBuilder is missing the setters on AllowLocalPeerDiscovery and AllowPortForwarding.  I'm curious about the design reasons for .ToSettings(), is that purely to convert the builder into the immutable Settings, or would you also use it to do settings validation? (e.g. if you had multiple settings that could clash).

**Comment by alanmcgovern** [comment]
> Hehe just trying this update I noticed the EngineSettingsBuilder is missing the setters on AllowLocalPeerDiscovery and AllowPortForwarding

Well oops! Turns out copy/paste is a great way to introduce bugs :p  That's fixed now!

> I'm curious about the design reasons for .ToSettings(), is that purely to convert the builder into the immutable Settings, or would you also use it to do settings validation?

It's currently intended purely as a means to create the immutable EngineSettings/TorrentSettings objects. Individual settings in the Builder have validations applied to them. If there is ever a case where individual properties are mutually exclusive then there'd have to be a choice made in how to support that. We may need:
- An atomic way to set two, or more, properties such that things are always in a compatible/consistent state.
- Add additional validations to the individual setters to ensure they throw immediately if anything is set in an incompatible way.
- Additional validations to make 'ToSettings' throw if the values are set incompatibly.

It's a bridge we can cross if/when we get there though!

**Comment by alanmcgovern** [comment]
Also, just to address the point in `EngineSettings.Equals()` and `EngineSettings.GetHashCode() ` not matching - they're not intended to.

Two objects which are equal must generate the same hashcode, but two objects which are different *may* also generate the same hashcode.

A subset of the properties are used for the GetHashCode impl as attempting to combine everything into one hashcode is unlikely to yield a better hashcode. Every property is in the `Equals` impl as this must be accurate.

**Comment by alanmcgovern** [comment]
I just issued a release containing these changes. You can test it out using the latest alpha from nuget, or by using tip of master!
