### ISSUE TITLE
[ .torrent ] File parsing Error in Monotorrent, when added url-list (http webseed url) option in [ .torrent ] File, created from Tixati, Transmission Client

### ISSUE THREAD

**Issue by wizard872** [alanmcgovern/monotorrent#332]
[ .torrent ] File parsing Error in Monotorrent, when added url-list (http webseed url) option in [ .torrent ] File, created from Tixati, Transmission Client

Tixati, Transmission

![image](https://user-images.githubusercontent.com/36080488/94421344-5e289a80-01c0-11eb-8eff-f61c0c71f02f.png)

but created from uTorrent, is work and not Parsing error.

uTorrent

![image](https://user-images.githubusercontent.com/36080488/94420831-ad220000-01bf-11eb-8d29-04422ce4b83d.png)

and i see .torrent file with HxD Hexeditor,

[HxD Hexeditor](https://mh-nexus.de/en/hxd/)

.torrent parsing ok, utorrent added url-list options, end of .torrent file like this,

![image](https://user-images.githubusercontent.com/36080488/94421584-bb245080-01c0-11eb-9ae3-e62ea54dcad7.png)

but .torrent parsing error  Tixati, Transmission is  added url-list options  start of .torrent file like this.

![image](https://user-images.githubusercontent.com/36080488/94421750-f888de00-01c0-11eb-9865-7b809167e003.png)

Probably, it seems to be a problem due to the different method of writing .torrent for each torrent client.

[ from google translate english  lol  :) ]

parsing error here.

![image](https://user-images.githubusercontent.com/36080488/94422175-a1cfd400-01c1-11eb-9808-f4d34e1a64a4.png)

MonoTorrent.BEncoding.BEncodeDecoder.cs
![image](https://user-images.githubusercontent.com/36080488/94422309-df346180-01c1-11eb-99d1-5fa63b634f23.png)

**Comment by samhocevar** [comment]
This is Tixati not fully following the torrent specification. It must store keys in lexicographical order, but as you can see the “url-list” entry is stored before the “created by” entry. Some torrent clients are more liberal than others in what they accept (I think MonoTorrent could accept to load such torrents, what do you think @alanmcgovern?)

I have posted a bug report on the Tixati website linking to this issue.

**Comment by alanmcgovern** [comment]
@samhocevar @wizard872 

The biggest issue with these kinds of torrents is that some clients will parse them, put the keys in the correct order, then compute the infohash. Other clients will compute the infohash using keys in the incorrect order.

The end result is that depending on which client you use you will get a different infohash, which makes everything tricky.

The spec says:
```
Note that this is a substring of the metainfo file. The info-hash must be the hash of the encoded form as found in the .torrent file, which is identical to bdecoding the metainfo file, extracting the info dictionary and encoding it if and only if the bdecoder fully validated the input (e.g. key ordering, absence of leading zeros). Conversely that means clients must either reject invalid metainfo files or extract the substring directly. They must not perform a decode-encode roundtrip on invalid data.
```

This means monotorrent can either reject these invalid torrents, or it can try to generate an infohash using the keys in the incorrect order. I went with rejecting invalid torrents as it's easier than maintaining the incorrect key order so we can compute that version of the infohash.

If we wanted to go with the latter approach, one option to support this would be to modify `Torrent.Load (Stream)`. Instead of calling `BEncodedValue.Decode` [here](https://github.com/alanmcgovern/monotorrent/blob/c1b6ceb401141ce76e91b44c246a6a005621378e/src/MonoTorrent/MonoTorrent/Torrent.cs#L563) we could instead call `BEncodedDictionary.DecodeTorrent`.

When we reach [this](https://github.com/alanmcgovern/monotorrent/blob/c1b6ceb401141ce76e91b44c246a6a005621378e/src/MonoTorrent/MonoTorrent.BEncoding/BEncodeDecoder.cs#L26) part of the code we should store the position of the stream right before we decode the 'info' dictionary, and immediately after we decode the 'info' dictionary and then calculate the infohash using the underlying Stream. Something like this...

```
if (InfoKey.Equals (key))
    infoDictStartOffset = Stream.Position;
value = DecodeDictionary (reader, strictDecoding: false); // always false
if (InfoKey.Equals(key))
    infoDictEndOffset = Stream.Position;

// hack things up and compute the infohash using the raw bytes as the keys may be unordered
var buffer = new byte[infoDictEndOffset  - infoDictStartOffset];
Stream.Seek (infoDictStartOffset);
Stream.Read(buffer, 0, infoDictEndOffset  - infoDictStartOffset);
using (SHA1 s = HashAlgoFactory.SHA1 ())
    computedInfoHash = s.ComputeHash (buffer);
```

We then would have to propagate the `computedInfoHash ` value back to Torrent.cs and use it [here](https://github.com/alanmcgovern/monotorrent/blob/c1b6ceb401141ce76e91b44c246a6a005621378e/src/MonoTorrent/MonoTorrent/Torrent.cs#L654) rather than computing it using the in-memory BEncodedDictionary.

@samhocevar or @wizard872 Let me know if either of you would like to try implement this idea and I can review the PR! Otherwise i might get around to it some time this week or early next!

**Comment by alanmcgovern** [comment]
Turns out I had most of the code in place already to make this really really easy :)

Implemented!

**Comment by alanmcgovern** [comment]
Backported an equivalent patch to 1.0 and will issue a new release with that change soon!

**Comment by samhocevar** [comment]
Tixati fixed the issue on their side, too (in version 2.78): https://forum.tixati.com/support/6829
