### ISSUE TITLE
New release changed some function. Unknown how to replace them with new version of GNU package

### ISSUE THREAD

**Issue by borrelnoten** [alanmcgovern/monotorrent#355]
I'm trying to replace the old function calls with the new but I'm stuck.

It used to work like this:

await engine.RegisterDhtAsync(new MonoTorrent.Dht.DhtEngine(MonoTorrent.Dht.Listeners.DhtListenerFactory.CreateUdp(dhtPort)));

and

await engine.EnablePortForwardingAsync(CancellationToken.None);

and

e.TorrentManager.Torrent.Files.BytesDownloaded  // where e is PieceHashedEventArgs

and

torrent.Files[0].BitField.PercentComplete

Please help finding the new function to use to replace the above (old) way of getting the torrent information

**Comment by alanmcgovern** [comment]
```
await engine.RegisterDhtAsync(new MonoTorrent.Dht.DhtEngine(MonoTorrent.Dht.Listeners.DhtListenerFactory.CreateUdp(dhtPort)));
```
Just set the `DhtPort property in `EngineSettings` to enable DHT. Everything else, including port forwarding for the Dht port, will be automatic.

```
await engine.EnablePortForwardingAsync(CancellationToken.None);
```
Set `EngineSettings.AllowPortForwarding = true`. This is the default value so you should set it to `false` if you want automatic port forwarding to be disabled.


```

**Comment by alanmcgovern** [comment]
I updated the release notes to make it a little clearer as to where these methods have gone :) https://github.com/alanmcgovern/monotorrent/releases/tag/release-v2.0.0-alpha.unstable.rev0017

**Comment by borrelnoten** [comment]
thank you for the fast reply! How about the DHT node files:

await engine.DhtEngine.StartAsync(nodes);

Is this also now different / automatic?

**Comment by borrelnoten** [comment]
e.TorrentManager.Torrent.Files.BytesDownloaded 

can't find Files.BytesDownloaded 

Also

torrent.Files[cur_torFileIndexNum].BitField

Can't find BitField

**Comment by alanmcgovern** [comment]
> So, should I now only user TorrentManager.Files instead of Torrent.Files?

Yes, i misread the original comment. This was a deliberate change to make the `Torrent` object immutable. All mutable state is in `TorrentManager.Files` now! This is also how you set the priority of a file too.

> await engine.DhtEngine.StartAsync(nodes);

If you want to load pre-saved nodes into the DhtEngine you can call this method as per usual. I may make a few changes around how to start/stop things to separate the lifespan of Dht and active torrents. Just because you stop all the torrents doesn't mean you want to stop the Dht engine, but those lifespans are linked at the moment.

If that does change it'll be in the release notes!

Let me know if you need anything else!
