### ISSUE TITLE
Will this project feature more than aria2?

### ISSUE THREAD

**Issue by BoyFaceGirl** [alanmcgovern/monotorrent#357]
Does the project know that the rpc protocol is supported? I don't understand c++, but I like .net and look forward to the monotorrent feature and user experience better than aria2.

**Comment by alanmcgovern** [comment]
I don't intend to write a full replacement for aria2. That would be beyond the scope of this particular library. 

An RPC protocol would be trivial to create if someone wanted to create a daemon, similar to aria2, which could be used to download in the background. The rpc calls would be used to interact with the daemon, rather than monotorrent itself, though. 

Hope that helps, and thanks for the support!
