### ISSUE TITLE
MonoTorrent 2.0 update exist torrent files issue

### ISSUE THREAD

**Issue by AN3Orik** [alanmcgovern/monotorrent#380]
Hi. I know 2.0 branch currently is unstable, but this is primarily a question, not a bug report.
I'm using MonoTorrent as update system for my program and when i tested today update with 2.0 branch - i got few broken files (~10Kb trash bytes in file) in result (this file exists in previous version and updated in new).  After i updated again - files become normal.
It's a known problem or i need collect more information and create issue?

**Comment by alanmcgovern** [comment]
Could you give me a little more detail describing what happened?

Was there a pre-existing file on disk which monotorrent was supposed to update and it faield to write the correct bytes? If so, does it look like there was exactly 16kB of data missing? It should write data in chunks of 16kB except for the very final piece, so if you can confirm the location of the corrupt bytes it might point to a missing Flush (or something) rather than a bug handling the data

**Comment by AN3Orik** [comment]
It's failed to write correct bytes. File size is ok. I notified broken files always different - so it's not related to specified file.

**Comment by AN3Orik** [comment]
P.S.: I compared 5 broken files and each file has 16Kb block of broken data.

**Comment by AN3Orik** [comment]
Hello again.
I noticed broken blocks appear in 100% cases in this torrents (~40Gb each)
1. Download 2886.torrent with qBitTorrent for example
2. Download 3078.torrent with qBitTorrent for example
3. Copy 2886.torrent downloaded content to another place, rename 2886 folder to 3078 and run 3078.torrent with MonoTorrent to update files 2886 to 3078 version in this folder
4. Compare originally downloaded 3078.torrent with updated from 2886 to 3078 via MonoTorrent (with BeyondCompare for example)
5. You must see ~15 broken files with 1-2 broken 16Kb blocks

[test_torrents.zip](https://github.com/alanmcgovern/monotorrent/files/5824813/test_torrents.zip)

**Comment by alanmcgovern** [comment]
Thanks for that! I was just working through some length piece picking improvements which have allowed me to remove the dedicated 'endgame' mode piece picker, and simplify the streaming picker.

This is next on my list. I'm still hoping it's as simple as a missing `Flush` invocation, but i'll dig into this problem next!

**Comment by alanmcgovern** [comment]
I tried testing with those torrents, but the torrent is so large it makes testing a bit awkward.

While I look into this in more detail, can you confirm if the issue goes away if you set `EngineSettingsBuilder.DiskCacheBytes` to zero and then instantiate your `ClientEngine`?

This will disable the in-memory disk cache and will help me narrow down whether you're seeing a bug in the memory cache or a bug in the how `DiskManager` handles writing data to different files concurrently.

**Comment by AN3Orik** [comment]
First of all: EngineSettingsBuilder.DiskCacheBytes isn't configurable at master for now (fix: https://github.com/AN3Orik/monotorrent/commit/ec487a2e6ac3e5eea54c59664b287350cac478a1)
But even with this fix `MemoryWriter` can't work with DiskCacheBytes == 0 (throwing AIOOB when trying writeAsync)
I didn't know how this work, so can't fix quickly for tests.

**Comment by alanmcgovern** [comment]
Oh, don't worry about further testing for now then! I'vr been digging into it this evening and I have a plausible theory I want to test out. 

I'm currently add some tests to ensure pieces which need to be written to the same file truly are queued and processed correctly. There are some tests covering this already but Im not 100% confident they prove the logic is correct. 

I'll merge fixes to allow setting the disk cache to zero, though setting it to a low value like 1 should also work in the same way. 

That said - if the issue goes away when you remove the memory writer completely then it's a great indicator that it's at least a contributing factor, if not the root cause. 

Thanks for that! I'll update you with more results tomorrow.

**Comment by alanmcgovern** [comment]
It looks like the engine is flushing all blocks of data after the final piece has passed it's hash check, but before the TorrentStateChanged event  is invoked to indicate the manager is in Seeding mode. This should be a strong guarantee that all data is written to disk. Either this isn't work as expected, or there's some (as yet) undiscovered threading issue. For a while I suspected the ReusableSemaphoreSlim, but after writing a few additional tests I couldn't trigger this kind of failure mode.

I'm going to disable the DiskCache by default for now. It does seem to be problematic and I should invest a bit more time in it before toggling it on again. This bug report is a sure enough sign that something is not right with it.

**Comment by alanmcgovern** [comment]
Just so you're aware - the disk cache is now disabled by default. It can only be modified by passing in a custom IPieceWriter when creating the ClientEngine. You'd have to do something like:

`new ClientEngine (...., new MemoryWriter (new DiskWriter (), 5 * 1024 * 1024)`

to create a MemoryWriter with a 5MB cache.


I'll probably issue a new alpha release tomorrow after a bit more testing of the recent changes to the PiecePicker interfaces and implementations. If the issue you're experiencing still surfaces then it's definitely *not* memory cache related and hopefully it'll show up for me too with the testing I'm intending on doing in the meantime.

Thanks!

**Comment by AN3Orik** [comment]
Ok, thanks. I'll test yr upcoming alpha and notify you about result.

**Comment by AN3Orik** [comment]
Hi.
Seams like broken blocks disappear at last build. But i'll test more to make sure all ok.

**Comment by alanmcgovern** [comment]
I've dug into this a bit more and with the latest refactoring around how the in-memory disk cache operates, this should be fully resolved.

I found one potential cause of this issue:
When a block of data arrives the engine checks if it can be incrementally hashed. If it can, then the piece is flushed straight to disk. If it cannot be incrementally hashed (i.e. blocks are received out of order) then the block is stored in-memory.

The issue was that if we are processing piece N and then receive piece N+1, piece N+1 would be considered to be *not* incrementally hashable a piece N is not hashed. This causes the piece to be written to the memory cache.

However, by the time the piece is written to the memory cache piece N may have finished being hashed, which then means we would actually succeed at incrementally hashing the block.

If this scenario occurred, the block would not be left in the memory cache until the cache files up and the oldest pieces are implicitly flushed.

If this happened for one of the final pieces, then the data would never be flushed.

**Comment by AN3Orik** [comment]
Thanks for your work! I'll try to push to production my tool with 2.0 MT version in few weeks and notify you if this problem appear again. But so far from my tests issue fully resolved. Thank you again.
