### ISSUE TITLE
1.0.29 not properly ignoring files

### ISSUE THREAD

**Issue by kinchims** [alanmcgovern/monotorrent#420]
Setting a file priority to DoNotDownload does not appear to be working in 1.0.29. Unless I am doing it incorrectly. I've tried setting this value before a torrent is started and after but it still downloads the files in question.

**Comment by alanmcgovern** [comment]
How are you determining this is not working correctly? Are you measuring how much data is downloaded, or can you see pieces associated with files marked as 'do not download' actually being downloaded, or are you simply looking at the files created in the output directory?

If you're looking at the files created by the engine, it's worth noting that the engine will create the file on disk if the first, or last, piece of the file needs to be downloaded due to it containing data for other files in the torrent.

On windows a sparse file is created so this is extremely efficient. On unix a full file is created so the full disk space will be consumed, but the data in the middle of the file won't be downloaded.

I'll double check this later to be sure there's no regression which was missed by the tests.

**Comment by kinchims** [comment]
After the torrent was in the seeding state I was checking the file structure on the drive and found that the I previously ignored were downloaded.

**Comment by alanmcgovern** [comment]
If I understand you correctly - this is normal and expected behaviour for files which are not downloaded. 

Files marked as DoNotDownload will exist on disk. A 1GB file may appear to be 1GB, but at most 2 x PieceLength bytes will actually be allocated - this will accommodate any data which is required to validate files which *were* downloaded. 

When the torrent is marked as Seeding what is the value of Progress and PartialProgress.foe the torrent manager? Also, what is the value of both of these properties if you call HashCheckAsync?

**Comment by kinchims** [comment]
It seems like you're correct; the progress & partial progress are both giving the correct percentages. My mistake for misinterpreting the result.

**Comment by alanmcgovern** [comment]
Great! Thanks for checking that for me. If you any other issues, or potential issues, please do open a ticket and I'll take a look!

I ran a quick test after work today anyway and things looked OK for me too.
