### ISSUE TITLE
After start and end pieces are complete, the download drops to 0

### ISSUE THREAD

**Issue by borrelnoten** [alanmcgovern/monotorrent#425]
After critical pieces are downloades usong filestream, the download drops to 0. After that, only when i seek to a piece that is not compleet yet, the download picks up again.

Could it be that the engine does not focus on other pieces after critical pieces are done?
I am using the latest nuget package.

Torrent URL: http://itorrents.org/torrent/75EB0E125B2EB0ECB363A63D03D9C16AF0C6990A.torrent?title=Watchmen-S01E01-iNTERNAL-1080p-WEB-h264-ROFL[rarbg]

**Comment by alanmcgovern** [comment]
I can only assume that the underlying reason is there are no seeders or leechers?

If you can reproduce issues in a healthier torrent please let me know. As it stands this one appears to be a dead torrent.

**Comment by borrelnoten** [comment]
I see it only has about 30Kb a second at this time. The files did get downloaded eventualy. Will keep an eye out. Tnx for checking.

**Comment by alanmcgovern** [comment]
Sounds good!

**Comment by borrelnoten** [comment]
Got another example for a torrent that dropped dead while the same torrent did go on using BitTorrent client. Monotorrent stopped at 5% download. Speed dropped to 0 bytes. 5 hours later, still 0 bytes speed. Started the BitTorrent client using the same torrent, it's downloading at 25+ Mb per second!

I've added a screenshot and the torrent file (as txt) in this note below:

![bitTorrent](https://user-images.githubusercontent.com/19395576/113105000-6c07b880-9201-11eb-9b39-91a082610991.png)

[Watchmen-S01E01-1080p-AMZN-WEBRip-DDP5-1-x264-KiNGS[rarbg].torrent.txt](https://github.com/alanmcgovern/monotorrent/files/6234508/Watchmen-S01E01-1080p-AMZN-WEBRip-DDP5-1-x264-KiNGS.rarbg.torrent.txt)

**Comment by alanmcgovern** [comment]
> To test, start stream torrent and seek to piece 0 and end piece. See what happens after that.

Ah, i think the problem you're seeing is that if you seek to the final piece, the engine is choosing to download nothing as there is no data *beyond* the point you're currently at. There is only data from *before* the current file position.

This is a bug - the engine is supposed to download in an order similar to:
* Super high priority pieces first (the piece we're actively reading and the next piece)
* High priority (the 16 pieces beyond the current one)
* Low priority (every piece *after* the high priority set)
* Literally anything (generally any piece *before* the current position).

The bug is that the engine is only doing 1, 2 and 3 at the moment. I you seek to piece 0, then the final piece, and then to piece 1 the issue would not occur. Does this description match what you're seeing?

**Comment by borrelnoten** [comment]
What would happen if i seek to a piece that is already downloaded?

**Comment by borrelnoten** [comment]
Oke. Can i start testing with latest nuget package?

**Comment by alanmcgovern** [comment]
I'll ship a new one tomorrow!

I want to add a couple of extra tests (just because I can) and I'll merge the PR then. 

If you want to test in the meantime you should be able to create a nupkg locally by checking out the branch and running "pack.bat" in a visual studio developer command prompt. The file will be placed in the "out" directory. 

Thanks for the report!

**Comment by alanmcgovern** [comment]
This should be in release 193 in nuget now!

**Comment by alanmcgovern** [comment]
I'll leave this open until you confirm the changes did help!

**Comment by borrelnoten** [comment]
Tests look good sofar. Will close if no issues next days.

**Comment by borrelnoten** [comment]
Tested and found no issues anymore.

**Comment by alanmcgovern** [comment]
Great! Thanks for that!
