### ISSUE TITLE
Piece Stream

### ISSUE THREAD

**Issue by ghost** [alanmcgovern/monotorrent#446]
Hello, please add the ability to load Piece yourself without using the file system.

Example
```
ClientEngine Engine = new ClientEngine();
var manager = await Engine.AddStreamingAsync(MagnetLink.Parse("magnet"), "test");
await manager.StartAsync();
await manager.WaitForMetadataAsync();

var stream = await manager.StreamProvider.CreatePieceStreamAsync(manager.Files[0], CancellationToken.None);

int pieceIndex = manager.Files[0].EndPieceIndex;
byte[] array= await stream.ReadAsync(pieceIndex);

if (array != null) return array;
```

1. In this mode, loading or creating a file on the disk does not occur, the client should only maintain an actual connection with trackers, but should not download blocks on its own.
2. The block should be loaded only at the moment of calling stream.ReadAsync (pieceIndex), but only the one that is specified
3. At the time of loading a block, the client should not load anything to disk or how the volume can interact with it, just after loading the blocks and issuing an array, the client should clear extra data in memory, as this is done when flushing the cache to disk.

**Comment by alanmcgovern** [comment]
You can create this custom behaviour by implementing an `IPiecePicker`/`IPieceRequester`, an  `IPieceWriter`/`IBlockCache`. It's been a while since you filed this, but do let me know if you you need more help!

If you don't want pieces to be requested you can customise IPieceRequester so it always returns `false` for the `bool IsInteresting` method, and then delegates to a normal 'StreamingPieceRequester` if you want to download normally.

If you want to avoid read/writing to disk then a custom IPieceWriter would do the trick. Or just write a customised `IBlockCache` which keeps everything in memory and never flushes to disk.
