### ISSUE TITLE
Hanging when download multiple metadata

### ISSUE THREAD

**Issue by depler** [alanmcgovern/monotorrent#452]
Code sample:

```
var link = MagnetLink.Parse("magnet:?xt=urn:btih:53276836AA0CEBC7BB9EECAEFB46417FA447EE1D");
using var engine = new ClientEngine();

var t1 = engine.DownloadMetadataAsync(link, CancellationToken.None);
var t2 = engine.DownloadMetadataAsync(link, CancellationToken.None);

await t1; 
await t2; //this will never end
```

**Comment by mfkl** [comment]
any logs?

**Comment by depler** [comment]
This is complete code sample, which reproduce bug in 100% of cases

**Comment by alanmcgovern** [comment]
Ah, this is actually quite a silly one.

If the issue you're experiencing is exactly as your sample describes, it's because `DownloadMetadataAsync` creates a `TorrentManager` under the hood, and your code snippet is hitting a bug which allows both invocations to `DownloadMetadataAsync` to add a `TorrentManager`for the same underlying torrent.

This will break some things within the engine. The most problematic example which comes to mind is when incoming connections are received. In this scenario the engine will pass them to the first `TorrentManager` with a matching infohash, as it expects there to be *exactly* one with a matching infohash. In this case all incoming connections will always go to the first torrentmanager.

I believe there are more places in the code which could break if the infohash is unintentionally loaded twice. I'll fix the code so the expected error is raised when this scenario occurs.
