### ISSUE TITLE
Delay before starting download

### ISSUE THREAD

**Issue by avdynut** [alanmcgovern/monotorrent#459]
I tested the `SampleClient` and I was discouraged that downloading is started in about 1 minute. While uTorrent downloads the same torrent file immediately.
Example torrent file: [https://webtorrent.io/torrents/sintel.torrent](https://webtorrent.io/torrents/sintel.torrent)

Please, someone, explain, what is the reason for the delay and how to avoid it?

**Comment by alanmcgovern** [comment]
I wonder if it's because all the trackers in that torrent are failing to respond so you're relying on Dht in order to retrieve any peers.

If you have disabled DHT, or if the DHT cache isn't being saved in between session, then that would explain why this is happening. DHT initialisation can take a little bit of time, and finding peers can be a little non-deterministic.

Can you check if there's a file called `dht_nodes.cache` in your `cache` directory? That's the one set by `EngineSettings.CacheDirectory`. If that file exists then the dht nodes are being cached/restored between sessions.
