### ISSUE TITLE
magnet link downloading

### ISSUE THREAD

**Issue by E4zily** [alanmcgovern/monotorrent#468]
tried this: 
`var manager = await engine.AddAsync(hash, Globals.directory);`
the download doesn't seem to be starting at all. what can i do?

**Comment by alanmcgovern** [comment]
i think what you're seeing is two different things:
1) The UdpListener (whichever one it is) is unable to bind to the port because something else has bound to it. You previously mentioned using a second bittorrent client. I suspect what you're seeing is that they're both trying to bind to the same ports? The listener's status should be set to 'PortNotFree' in that case. I think this could be surfaced more clearly.

2) tracker.opentrackr.org was probably not responding at the time.

that said, without the actual logs and a way to reproduce the problem i won't really be able to make any reasonable suggestions.

**Comment by alanmcgovern** [comment]
If you have any further questions let me know!
