### ISSUE TITLE
Add CheckMissingFiles option to Engine

### ISSUE THREAD

**Issue by YegorStepanov** [alanmcgovern/monotorrent#494]
#### Current behavior:
* Add torrent file to the app
* Close app
* Delete downloaded files
* Open app
* The engine restores a state of the torrent. I can Pause/Resume torrent, but `Paused`/`Downloading` are incorrect states here.

#### Suggestion:
Add an option to the engine, that will additionally check the existence of files.

IO is expensive, but `Monotorrent` opens these files anyway. It would be great if the library would do it, otherwise the library customers should duplicate IO-requests and handle with `.State + bool isMissing` logic.

#### Question:
Should be **`MissingFiles`** displayed too when the user changes files (a wrong file's hash)?

**Comment by YegorStepanov** [comment]
Hmm, It's works correctly.

I have saw "the file is busy by some process" exceptions when calling `Resume` few times. I will try to find who is blocking the file.

**Comment by alanmcgovern** [comment]
> I have saw "the file is busy by some process" exceptions when calling Resume few times. I will try to find who is blocking the file.

Hrmm, do you know if monotorrent is holding those files open, or if you have a second application opening the files? If a second application is involved, and you're in control of that application, make sure you open files with the `FileShare.Read` or `FileShare.ReadWrite` permissions otherwise monotorrent won't be able to open them for reading/writing.

If MonoTorrent is incorrectly keeping these files open let me know and i'll look into it!

**Comment by YegorStepanov** [comment]
Nobody uses files. OneDrive doesn't scan the folder.

I have played with two 1GB torrent files. 

After some hours running of VS, I have 0b on disk C.  When I close the VS, it frees 30GB. The RAM pressure is ~80%. (8Gb of RAM). I don't checked yet is it due to the page swapping or the files generate infinitely somewhere.

The MonoTorrent folder is 50Kb, so I think I somewhere have a memory leak, but Win11/VS2022/WinUI3 not frees it after closing the debug app.
