### ISSUE TITLE
[Question] How does 'Hashing' work? (Recheck of downloaded files)?  It appears my re-hash of 40GB finished rather quickly

### ISSUE THREAD

**Issue by jeffward01** [alanmcgovern/monotorrent#515]
Hello!

I was working with and testing out the `TorrentManager` [File Hasher](https://github.com/alanmcgovern/monotorrent/blob/b0c484684c708bfee4d92c06178f1e64d2cc4399/src/MonoTorrent.Client/MonoTorrent.Client.Modes/HashingMode.cs). 

I ran a hashcheck, and this was the sequence of events:

* I have a torrent which is approximately 40GB in size and has been downloaded to my local computer.  
* The `manager.PieceLength` showed me: 16777216 total pieces
* I started the hash check
* The hash check seemed to be rather 'slow', after a few minutes it had only checked up to the piece index of 3,400 / 16777216 
* I minimized the screen
* At the timestamp of `13 minutes and 7 seconds` the Hash Check was complete without errors.

This seems rather fast to me, I am wondering if my understanding of how a 'Hash Check' works is correct.  

## Questions

1. Will the Hashcheck check all 16777216 pieces?

2. I attempted to create a progress bar, and 3400 out of 16777216 pieces is very small, so it showed 0.00% (this is expected), It is surprising that it finished so quickly. What could have happened?

3. Is there anyway to 'speed up' the hashcheck? I think not because it is limited to how fast the machine can has a `MD5 Hash`.

---

Thanks all!!

**Comment by alanmcgovern** [comment]
Hey!

Thanks for the questions. Hopefully this will help!

> * At the timestamp of `13 minutes and 7 seconds` the Hash Check was complete without errors.
> 
> This seems rather fast to me, I am wondering if my understanding of how a 'Hash Check' works is correct.

Hashing 40GB in 13 minutes is about... 50MB/sec. That's a reasonable lower-bound for how fast things should be on 'modern' hardware. My own (somewhat slow) laptop averages about 100MB/sec, which would hash 40GB in approx. 

> 
> ## Questions
> 1. Will the Hashcheck check all 16777216 pieces?
If all the data is available on disk, then yes!

> 2. I attempted to create a progress bar, and 3400 out of 16777216 pieces is very small, so it showed 0.00% (this is expected), It is surprising that it finished so quickly. What could have happened?

If any data is not available on disk, you could hit the fast path. For example, if there's a 10GB file in the torrent and only the first piece has been downloaded, monotorrent can tell that the file is too short and will not actually try to read/hash the data which *does not exist*. This makes hashing incomplete files significantly faster.

> 3. Is there anyway to 'speed up' the hashcheck? I think not because it is limited to how fast the machine can has a `MD5 Hash`.

I suspect the limiting factor here is that the process is less parallel than it *could* be. There's probably some improvements there which could improve the throughput when doing large sequential reads.

At the least, DiskManager.GetHashAsync could be changed so that it can perform reads in parallel with invoking `incrementalHash.AppendData`. A double-buffer system could be used so that buffer0 is filled with data first, then you enter a loop and do:
```
await ReadAsync (first_block, buffer0);

while (data_remaining) {
    // read the next block of data asynchronously
    var readingTask = await ReadAsync (next_piece, buffer1);

    // hash this while we're waiting for the other data to read.
    incrementalHash.AppendData (buffer0);

    // wait for the read task to complete
    await readingTask;

    // swap the buffers so we can continue
    (buffer0, buffer1) = (buffer1, buffer0);
}

// probably need to append the final buffer now.
incrementalHash.AppendData (buffer0);
```
If you're interested in trying that change to see if it helps, it should be pretty reasonable to code it up! There may be some other tricks which can make this faster, but I'd probably want to see some comparisons between bittorrent clients before trying to optimise this too much.

**Comment by alanmcgovern** [comment]
There's one other option too.

At the moment `FileStream` objects are always created using `FileOptions.RandomAccess`. It's possible that there'd be a performance boost if `FileOptions.SequentialScan` were used during a full hashcheck. To make this work we'd have to hint to the DiskManager that a full hash is about to happen so it can (re-)open the underlying filestream with the new hint.

**Comment by jeffward01** [comment]
@alanmcgovern -- Big thanks for getting back to me on this! I have just seen your replies, I will review them and comment back!

BTW - I have reviewed may Torrent Clients, and bittorrent Libs in C# and other languages (I am a C# only dev), and by far MonoTorrent is the best! Excellent work!! <3

**Comment by alanmcgovern** [comment]
I'll assume everything is OK for now!
