### ISSUE TITLE
Blazor Webassembly

### ISSUE THREAD

**Issue by AliShahesmaeili** [alanmcgovern/monotorrent#539]
Is this library usable in blazor webassembly .net 6?
I just want to download a torrent file

I get an exception when I make a ClientEngine
`using var engine = new ClientEngine(settings);`

_System.PlatformNotSupportedException_

**Comment by alanmcgovern** [comment]
I've never explicitly tried blazor.

Do you know which API is raising the PlatformNotSupportedException?

**Comment by AliShahesmaeili** [comment]
@alanmcgovern 
https://docs.microsoft.com/en-us/dotnet/core/compatibility/cryptography/5.0/cryptography-apis-not-supported-on-blazor-webassembly

You are using System.Security.Cryptography apis in MonoTorrent.BEncoding project ...

Is there no way to use this library in Blazor WebAssembly? (MonoTorrent.BEncoding is necessary? for download a torrent file)

https://github.com/dotnet/designs/blob/main/accepted/2021/blazor-wasm-crypto.md
(Cryptographic support seems to will be add to .NET 7 in blazor wasm)

**Comment by alanmcgovern** [comment]
You can't download a torrent unless you can load the .torrent metadata. 

Doing so requires the ability to parse BEncoded files. That also requires SHA1 and SHA256 in order to calculate the infohash. 

Cryptography classes/methods are used for merkle trees and piece validation, so there's no way around this other than reimplementing any of the required code so the direct reference to the various System.Security.Cryptography apis can be removed. 

It's not something I'd be particularly interested in accepting patches for as maintaining a secure and performance cryptography stack is quite a burden.

If these apis are available in .NET 7 then I'd expect waiting for that to ship would be the best option. 

Are they they only blocking issue that you're aware of?

**Comment by alanmcgovern** [comment]
I'll close this for now as there's not much to do until blazor supports a more reasonable subset of the BCL. 

Thanks for reporting, and do let me know if a future release of blazor can be supported with a smaller set of changes!
