### ISSUE TITLE
Selective file downloading (including the ability to not download specific files).

### ISSUE THREAD

**Issue by BoyFaceGirl** [alanmcgovern/monotorrent#553]
How does this function work? How to get the magnetic link or the files contained in torrent before starting the official download? I am developing a program, hoping to obtain the list of downloaded contents before downloading, so that users can select the problems they want to download. However, there are no similar examples or documents telling me how to set files that do not need to be downloaded. Thank you again for your efforts.

magnet:?xt=urn:btih:9669CE256DDB3667F81D3FE36D857956C423115A&dn=CentOS-8.1.1911-x86_64-boot.iso

**Comment by luandersonn** [comment]
Set the file priority to `DoNotDownload`:

```cs
TorrentManager torrent; 
// ...
foreach(ITorrentFileInfo file in torrent.Files)
    await torrent.SetFilePriorityAsync(file, Priority.DoNotDownload);
```

**Comment by BoyFaceGirl** [comment]
> Set the file priority to `DoNotDownload`:
> 
> ```cs
> TorrentManager torrent; 
> // ...
> foreach(ITorrentFileInfo file in torrent.Files)
>     await torrent.SetFilePriorityAsync(file, Priority.DoNotDownload);
> ```

Thank you for your reply. My biggest problem now is that torrent. Files. Count = = 0, so it can't be used. I have found the problem of torrent. Files. Count = = 0. Monotorrent can not always find the torrent corresponding to the magnetic link effectively

**Comment by alanmcgovern** [comment]
There are a few options for this.

1) Call `TorrentManager.WaitForMetadataAsync`. When downloading using a magnet link, this method will return once the metadata has been received and loaded. At this point you'll have access to `TorrentManager.Torrent`, and `TorrentManager.Files` will be non-empty.

2) You could attach an event handler to `TorrentManager.TorrentStateChanged` and wait for `e.OldState` to `TorrentState.Metadata`. When this occurs you should check if `TorrentManager.Files` and `TorrentManager.Torrent` are non-null. If the torrent manager was stopped before the metadata had been received they'll still be null, otherwise they'll be non-null/empty and you can set priority for individual torrents as needed.

3) Use `ClientEngine.DownloadMetadataAsync` to download metadata first. Once this has been received, you can save it to disk or just load it directly into the engine. This gives a very clear distinction between the "trying to download metadata" phase and then "i want to selectively download some files in this torrent" phase.

Let me know if there are other options which would make this easier!

**Comment by BoyFaceGirl** [comment]
> 对此有几个选择。
> 
> 1. 叫。使用磁力链接下载时，此方法将在接收并加载元数据后返回。此时，您将有权访问 ，并且该访问将不为空。`TorrentManager.WaitForMetadataAsync``TorrentManager.Torrent``TorrentManager.Files`
> 2. 您可以将事件处理程序附加到 并等待 到 。发生这种情况时，您应该检查 是否为非空。如果种子管理器在收到元数据之前已停止，它们仍将为空，否则它们将非空/空，您可以根据需要为单个种子设置优先级。`TorrentManager.TorrentStateChanged``e.OldState``TorrentState.Metadata``TorrentManager.Files``TorrentManager.Torrent`
> 3. 用于首先下载元数据。收到此文件后，您可以将其保存到磁盘或直接将其加载到引擎中。这在“尝试下载元数据”阶段和“我想在这个洪流中有选择地下载一些文件”阶段之间有非常明显的区别。`ClientEngine.DownloadMetadataAsync`
> 
> 让我知道，如果有其他选项可以使这更容易！

**Comment by BoyFaceGirl** [comment]
> There are a few options for this.
> 
> 1. Call `TorrentManager.WaitForMetadataAsync`. When downloading using a magnet link, this method will return once the metadata has been received and loaded. At this point you'll have access to `TorrentManager.Torrent`, and `TorrentManager.Files` will be non-empty.
> 2. You could attach an event handler to `TorrentManager.TorrentStateChanged` and wait for `e.OldState` to `TorrentState.Metadata`. When this occurs you should check if `TorrentManager.Files` and `TorrentManager.Torrent` are non-null. If the torrent manager was stopped before the metadata had been received they'll still be null, otherwise they'll be non-null/empty and you can set priority for individual torrents as needed.
> 3. Use `ClientEngine.DownloadMetadataAsync` to download metadata first. Once this has been received, you can save it to disk or just load it directly into the engine. This gives a very clear distinction between the "trying to download metadata" phase and then "i want to selectively download some files in this torrent" phase.
> 
> Let me know if there are other options which would make this easier!

@alanmcgovern 

Is it impossible to download seeds directly from the magnetic link warehouse through the magnetic force now? Download the seeds directly from the seed warehouse according to the magnetic link information. such as

magnet:?xt=urn:btih:f8181597b51c157fb470e5ee236e364c6fbc2af2

Use btbox warehouse:

infohash=f8181597b51c157fb470e5ee236e364c6fbc2af2.ToUpper()

download  url =http://bt.box.n0808.com+"/"+infohash.Substring(0,2) +"/"+infohash.Substring(infohash.length-2,2)+"/"+infohash+".torrent"


There are also many seed warehouses that can directly construct torrent file download websites through magnetic links, which is much faster than downloading through DHT search. Of course, this function can be set as an optional option. If the search fails, search the toorent file through DHT
