### ISSUE TITLE
Sort mismatch between v1 and v2 files leads to "Inconsistent hybrid torrent, mismatch in v1 and v2 files" exception

### ISSUE THREAD

**Issue by borigas** [alanmcgovern/monotorrent#563]
V1 and V2 torrents are sorting file lists differently. V1 is sorted files 1st, then child directories. V2 is sorted by the relative path to the root of the torrent. This leads to an exception in `Torrent.ProcessInfo()`

```
[Test]
public async Task DirectorySortInHybrid ()
{
    var dir = new DirectoryInfo (nameof (DirectorySortInHybrid));
    if (dir.Exists)
        dir.Delete (true);

    dir.Create ();

    var eFile = new FileInfo (Path.Combine (dir.FullName, "E.file"));
    File.WriteAllText (eFile.FullName, "aoeu");

    var bFile = new FileInfo (Path.Combine (dir.FullName, "B.file"));
    File.WriteAllText (bFile.FullName, "aoeu");

    var aFileInDir = new FileInfo (Path.Combine (dir.FullName, "Dir/A.file"));
    if (!aFileInDir.Directory.Exists)
        aFileInDir.Directory.Create ();
    File.WriteAllText (aFileInDir.FullName, "aoeu");

    ITorrentFileSource fileSource = new TorrentFileSource (dir.FullName);
    TorrentCreator torrentCreator = new TorrentCreator (TorrentType.V1V2Hybrid);
    var encodedTorrent = await torrentCreator.CreateAsync (fileSource);
    var torrent = Torrent.Load (encodedTorrent);

    Assert.IsNotNull (torrent);
}
```

![image](https://user-images.githubusercontent.com/2268265/197839988-d9afafec-60b4-4ea2-8f7f-6c6c34cebebd.png)

**Comment by alanmcgovern** [comment]
Thanks for the testcase, it made things much easier to figure out!

I was just looking through this and I realised what was occurring was that for v1 torrents the files would be hashed in the same order they were passed to the TorrentCreator. This was 'standard' behaviour and allowed people to pack files in a specific order.

For V2 or Hybrid torrents, the implicit part of the spec was that files *must* be sorted prior to hashing them as the list of files is now stored in a bencoded dictionary as opposed to a bencoded list.

In this case, the fix is to sort the list of files in `TorrentCreator`. I'll take a look through this in some more detail tomorrow, but do let me know if this fixes your case!

**Comment by borigas** [comment]
Yep, seems to work. Thanks for the fix!
