### ISSUE TITLE
Torrent create progression

### ISSUE THREAD

**Issue by foxi69** [alanmcgovern/monotorrent#570]
Is there any way to show the progression in 2 digits? Like 0,5,10, 20... 100% etc?

```
torrentCreator.Hashed += (o, e) => {
             Console.WriteLine(e.OverallCompletion);
};
```

**Comment by alanmcgovern** [comment]
This is a value between 0 and 1, so you can format it as a percent using the standard format specifier for percentages: `p`: https://learn.microsoft.com/en-us/dotnet/standard/base-types/standard-numeric-format-strings

Or just multiply it by 100 and add a % sign :)

**Comment by alanmcgovern** [comment]
That kind of determination is hard to make at the library level. Some people care about overall progress, some people care about progress in a per file level, some care about getting updates on a timed interval.

It's probably easiest if you have decide which you care about most, and then implement a small wrapper around the event which implements the particular rate limiting you need for your usecase. 

Do let me know if there's a specific usecase you can't support using the existing event and/or APIs in the library.

**Comment by alanmcgovern** [comment]
> but this progression will be five times 100%

This is the expected behaviour if the final piece in the torrent contains data from 5 different files. In this scenario this loop will execute once per file: https://github.com/alanmcgovern/monotorrent/blob/e3da4c22c4d966191b34cfa674365df3679df3df/src/MonoTorrent.Client/MonoTorrent/TorrentCreator.cs#L428-L429 . The value for `overallHashed` and `overallTotal` will be the same for each of these events, however the `file` parameter will be different. This ensures that there will always be an event for each file where `fileHashed` is the same as `fileTotal`, implying the file has been fully hashed.

If you see 100% appear multiple times when the final piece of the torrent contains data from just 1 file, then there's a bug. If so, is there a sample you can share to help me reproduce the issue?
