### ISSUE TITLE
Failed to compare two elements in the array. - Monotorrent v3.0.0-beta.rev0102

### ISSUE THREAD

**Issue by foxi69** [alanmcgovern/monotorrent#581]
```
System.InvalidOperationException
Message : Failed to compare two elements in the array.
StackTrace :    at System.Collections.Generic.GenericArraySortHelper`1.BinarySearch(T[] array, Int32 index, Int32 length, T value, IComparer`1 comparer)
   at System.Array.BinarySearch[T](T[] array, Int32 index, Int32 length, T value, IComparer`1 comparer)
   at System.Collections.Generic.SortedList`2.Add(TKey key, TValue value)
   at MonoTorrent.BEncoding.BEncodeDecoder.DecodeTorrent(Stream reader)
   at MonoTorrent.Torrent.Load(Stream stream, ReadOnlySpan`1 buffer)
   at MonoTorrent.Torrent.Load(String path)
   at MultiUploader.Helpers.Torrents.IsImageFromTorrent(String torrentFile)
System.BadImageFormatException
Message : Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058)
StackTrace :    at System.ReadOnlyMemory`1.get_Span()
   at MonoTorrent.BEncoding.BEncodedString.CompareTo(BEncodedString other)
   at System.Collections.Generic.GenericArraySortHelper`1.BinarySearch(T[] array, Int32 index, Int32 length, T value)
   at System.Collections.Generic.GenericArraySortHelper`1.BinarySearch(T[] array, Int32 index, Int32 length, T value, IComparer`1 comparer)
System.BadImageFormatException
Message : Cannot load a reference assembly for execution.
```

My Code is:

```
foreach (TorrentFile file in Torrent.Load(torrentFile)) {
         if (Regex.IsMatch(file.Path, "^.*\.(iso|cue)$", RegexOptions.IgnoreCase)) {
             return true;
         }
     }
 }
 return false;
```

**Comment by alanmcgovern** [comment]
Hrm, this looks like a miscompilation of some sort. The BadImageFormat error could be the thing at fault here. 

Can you share a self contained compilable repro? Alternatively, does the issue occur if you make a brand new console app project and run the same code? 

Which framework version are you targeting with your project anyway?

**Comment by alanmcgovern** [comment]
Hrm, if I create a brand new project which targets .NET 4.7.2 and reference the latest MonoTorrent 3.0 beta from NuGet.org, i get this compilation failure:

```
Error	CS0012	The type 'ReadOnlySpan<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
```

I would've expected your application to fail to compile in the same way until that reference is added. However, I believe I can update the nuget to make this reference explicit! Let's see...

**Comment by alanmcgovern** [comment]
[tester.zip](https://github.com/alanmcgovern/monotorrent/files/10203226/tester.zip)
[MonoTorrent.3.0.0-beta.rev0102.zip](https://github.com/alanmcgovern/monotorrent/files/10203227/MonoTorrent.3.0.0-beta.rev0102.zip)

I attached a copy of the nuget where the reference to System.Memory is explicitly set. This seems to work for me! I also attached the sample project, which reference NET4.7.2, so you can see how I tested it.

Can you let me know if your project works when that version of monotorrent is used?

**Comment by alanmcgovern** [comment]
Huh, I got that error with the existing release in nuget.org, but when using the rev102 nugget I attached above it worked fine :s

What happens if you add an explicit reference to the System.Memory nuget in the Tester project? Does that make it work again?

**Comment by alanmcgovern** [comment]
Also, could you expand the `Dependencies` in the solution explorer and show me what shows up by default for you when you open a clean/unmodified copy of the Tester project. Mine looks like this, and has the System.Memory reference included by default:

![example](https://user-images.githubusercontent.com/264396/206928688-a4feaaa3-0d02-4418-bda7-e16bba082a25.png)

**Comment by alanmcgovern** [comment]
And what happens if you manually add a reference to the System.Memory nuget package? Does that make the sample compile/run correctly?

Finally, what version of Visual Studio are you using? I wonder if there's a bug in either your version or mine which is causing this mismatch. I'll downgrade/upgrade to match your version (assuming I can) and that should help me fix this properly.

**Comment by alanmcgovern** [comment]
> > Does that make the sample compile/run correctly?
> 
> Yes, but after I create a Visual Studio Installer Project, then i installed the app the error comes again. It works until i run it in visual studio project

Could you share a copy of an Installer project which reproduces the issue, similar to the "Tester" project I shared. Could you also let me know which version of visual Studio you're using?

This sounds like a packaging bug where something isn't including the full set of dependencies, and that's going to be hard to resolve without a way to repro the issue :(

**Comment by alanmcgovern** [comment]
Oh interesting! It looks like the installer is broken and is including the reference assembly, not the implementation assembly, when creating the package!

Let's see if i can find a related bug/workaround...

**Comment by alanmcgovern** [comment]
This appears to be the bug - https://github.com/NuGet/Home/issues/9310 - though the workaround listed there hasn't (yet) worked for me!

I'll look a bit more :s

**Comment by alanmcgovern** [comment]
![still_ref_assembly](https://user-images.githubusercontent.com/264396/207136199-9bf03d06-2d85-41f8-b4a9-ee8f473ab614.png)

I can definitely see the `ref` assembly listed here... but that shouldn't happen :(

**Comment by alanmcgovern** [comment]
Some bug reports say that this only happens if you use `<PackageReference />` and convert to the old `package.config` style fixes it. I gave it a shot but that didn't work either.

This is a pretty clear bug with the visual studio installer thing, and I'm not familiar enough with it to understand how to configure it to do the right thing. I'm surprised the workarounds linked from the previous bug report aren't working in this scenario.

There are some other suggestions here which are alternatives to ensure the right set of libraries are included in the installer:
https://developercommunity.visualstudio.com/t/visual-studio-installer-projects-extensions-incorr/810090

The only option i can think of that seems reliable would be to remove `Primary Output` from the list of things which are included in the installer, and then use the `add -> assembly` option to explicitly list the files you want from the 'Debug' or 'Release' folder. The correct subset of files should be in that directory as those are the ones used when you hit F5 to debug.

This is a really annoying workaround as you (probably?) would have to create two different installer projects - one for 'Debug' assemblies and one for 'Release' assemblies, unless you know how to parameterise those references.

This is the method which will *probably* work:

![test](https://user-images.githubusercontent.com/264396/207174113-6817f308-8818-4f57-a36b-767bf0941e82.gif)

**Comment by alanmcgovern** [comment]
> Doesn't work for me :(

As in explicitly listing the set of assemblies still results in a broken installer? If so i'm surprised because the assemblies in the `bin` directory are the ones used when you launch the app in the debugger, so packaging them should result in a working installer. I didn't follow all the steps to the end to create a 100% working installer. I can run through those steps if you think there's still something i can/need to fix with the actual monotorrent nuget dependencies!

> Is there any other package which can create exe?

I've used wix in the past for this kind of thing (https://wixtoolset.org/). It might be worth looking at it as an alternative?

> but why everything works great with the version of 2.0.6 (except torrent create progress)?

2.x didn't use `Memory<T>` or `Span<T>` and so didn't need a reference to the `System.Memory` nuget package, which is what provides those types for .NET Standard 2.0 compatible frameworks ( https://www.nuget.org/packages/System.Memory/#readme-body-tab ). This includes .NET 4.7.2 and .NET 4.8.x.

Having a dependency like this shouldn't be a problem as the installer *should* be able to pick up these deps and do the right thing. The other dependencies of the library are https://www.nuget.org/packages/ReusableTasks and https://www.nuget.org/packages/Mono.Nat, so you should have this problem for *all* of those or *none* of those.

**Comment by alanmcgovern** [comment]
<img width="398" alt="deps" src="https://user-images.githubusercontent.com/264396/207946402-234fe47b-9eb5-4d45-94b7-583ca30952fd.png">

These are the dependencies the MonoTorrent nuget package has for the latest release. System.Memory is now listed for the .NETStandard 2.0 target, which is what is used for .NET 4.7.2 and 4.8.x

**Comment by MSLukeWest** [comment]
@alanmcgovern @foxi69 I tried this scenario using the supplied project in TestAppInstaller.zip, and in my testing I found that _both_ workarounds fix the issue where reference assemblies are taken from NuGet packages.  Here's what I did:

1) Built the sample app as is, and saw that there were six reference assemblies being copied from NuGet packages:

%NugetCachePath%\system.buffers\4.5.1\**ref**\net45\System.Buffers.dll
%NugetCachePath%\system.drawing.common\5.0.3\**ref**\net461\System.Drawing.Common.dll
%NugetCachePath%\system.numerics.vectors\4.5.0\**ref**\net46\System.Numerics.Vectors.dll
%NugetCachePath%\system.runtime.compilerservices.unsafe\4.5.3\**ref**\net461\System.Runtime.CompilerServices.Unsafe.dll
%NugetCachePath%\system.security.principal.windows\4.0.0\**ref**\net46\System.Security.Principal.Windows.dll
%NugetCachePath%\system.valuetuple\4.5.0\**ref**\net47\System.ValueTuple.dll

2) Unzipped into a separate folder and converted the project back to packages.config.  This took a while and involved manually adding each package back through NuGet Package Manager (there might be an easier way).  After this I did a clean, then built, and I no longer see any reference assemblies coming from NuGet packages.  I confirmed that those 6 assemblies are included, and they're all the "real" versions:

TesterApp\packages\System.Buffers.4.5.1\**lib**\net461\System.Buffers.dll
TesterApp\packages\System.Drawing.Common.5.0.3\**lib**\net461\System.Drawing.Common.dll
TesterApp\packages\System.Numerics.Vectors.4.5.0\**lib**\net46\System.Numerics.Vectors.dll
TesterApp\packages\System.Runtime.CompilerServices.Unsafe.4.5.3\**lib**\net461\System.Runtime.CompilerServices.Unsafe.dll
TesterApp\packages\System.Security.Principal.Windows.4.0.0\**lib**\net46\System.Security.Principal.Windows.dll
TesterApp\packages\System.ValueTuple.4.5.0\**lib**\net47\System.ValueTuple.dll

3) Unzipped into another separate folder, and this time added the target from the comment in https://github.com/NuGet/Home/issues/9310 into the bottom of the csproj file, just above the closing Project tag.  After this I did a clean, then built, and I see the same result, no reference assemblies came from Nuget packages:

%NugetCachePath%\system.buffers\4.5.1\lib\net461\System.Buffers.dll
%NugetCachePath%\system.drawing.common\5.0.3\lib\net461\System.Drawing.Common.dll
%NugetCachePath%\system.numerics.vectors\4.5.0\lib\net46\System.Numerics.Vectors.dll
%NugetCachePath%\system.runtime.compilerservices.unsafe\4.5.3\lib\net461\System.Runtime.CompilerServices.Unsafe.dll
%NugetCachePath%\system.security.principal.windows\4.0.0\runtimes\win\lib\net46\System.Security.Principal.Windows.dll
%NugetCachePath%\system.valuetuple\4.5.0\lib\net47\System.ValueTuple.dll

So, while I can't confirm this makes the app work, I do think it's worth revisiting these workarounds (specifically the much simpler one explained in 3 above) and taking a closer look at what's failing.

A couple notes:
1) I did this testing in a recent Visual Studio 2022 preview build, but I'd expect the released VS 2022 Update 4 or soon to be released Update 5 builds to show the same behavior.
2) My testing was aided by this extension, which produces .binlog files for the build performed by VS: https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.ProjectSystemTools2022.  You can see what files get added to the installer by seeing what gets added during the targets "BuiltProjectOutputGroup" and "BuiltProjectOutputGroupDependencies".
3) Make sure to do a Clean in VS, delete obj/bin folders, and clean the local solution package cache after doing the conversion
