### ISSUE TITLE
Using MoveFileAsync causes FullPath to be neither DownloadIncompleteFullPath nor DownloadCompleteFullPath

### ISSUE THREAD

**Issue by ManlyMarco** [alanmcgovern/monotorrent#606]
Using MoveFileAsync to move a torrent file changes its `ITorrentManagerFile.FullPath`, but not `DownloadIncompleteFullPath` nor `DownloadCompleteFullPath`. After the download finishes, the file is moved to `DownloadCompleteFullPath` while `FullPath` stays as whatever was used in MoveFileAsync

The documentation states: `If the file is currently being downloaded, this will be the same as <see cref="DownloadIncompleteFullPath"/>. Otherwise it will be <see cref="DownloadCompleteFullPath"/>`

The below is what I get after using MoveFileAsync to move the file to a temporary path, then waiting for the torrent to finish downloading and stopping it.
```
DownloadIncompleteFullPath=F:\.....\test.bin 
DownloadCompleteFullPath=F:\.....\test.bin 
FullPath=F:\temp\pk0h5mbi.mbu
```

Tested on 3.0.0-beta.rev0106

Edit: It looks like two copies of the file exist right at the end of a download, one in FullPath and one in DownloadCompleteFullPath.

**Comment by alanmcgovern** [comment]
Could you let me know if the changes in that branch ( https://github.com/alanmcgovern/monotorrent/pull/608 ) fix the issue for you?

There were tests ensuring the right thing happened when toggling `UsePartialFiles` on/off, but there were no tests ensuring things were in sync after `MoveFilesAsync` was invoked... and, well, that's why it flat out didn't work!

This tests those cases now, and it also ensures that the on-disk files are also in the correct place.

**Comment by ManlyMarco** [comment]
The issue appears to be fixed in that branch, thanks!
