### ISSUE TITLE
I don’t know what to do with this anymore

### ISSUE THREAD

**Issue by scorpionsFC** [alanmcgovern/monotorrent#647]
I use version 3.0, but always Connection failed: ipv4://188.138.169.149:32747/ - EncryptionNegiotiationFailed

![Безымянный](https://github.com/alanmcgovern/monotorrent/assets/7205961/be45b563-b84c-4cf8-a1e1-c7a9ca302f6c)

but when I restart the distribution, it starts to download.

**Comment by alanmcgovern** [comment]
I'm unsure what the issue is either based on that output. If the torrent is publicly/freely available and can be shared, please do! Otherwise it'll take some digging to understand exactly what's going on.

That particular failure string should likely be changed. It's more indicating that *negotiation* failed as it is emitted whether the 'encryption' is plain text, or full RC4.

If it's reproducible, please let me know!
